config/routes.rb
Rails.application.routes.draw do
  get 'resumes/index'
  get 'resumes/new'
  get 'resumes/create'
  get 'resumes/destroy'
  devise_for :users
  get 'welcome/index'
  root 'welcome#index'

  get 'images/bin'
  get 'images/classify'

  resources :articles, only: [:new, :show, :create, :edit, :update, :destroy]
  resources :resumes, only: [:index, :new, :create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/models/resume.rb
class Resume < ApplicationRecord
  mount_uploader :attachment, AttachmentUploader
  validates :name, presence: true

  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :resumes, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.save
  end

  def show
    @article = Article.find(params[:id])
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    if @article.update(article_params)
      flash[:notice] = "Article was updated"
      redirect_to article_path(@article)
    else
      flash[:notice] = "Article was not updated"
      render 'edit'
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    flash[:notice] = "Article was deleted"
    redirect_to root_path
  end

  private
    def article_params
      params.require(:article).permit(:title, :preview, :content, :thumbnail);
    end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  def bin
    image_bin = `ls -tr /home/bohdan/Desktop/recognazing/Recognizing/public/uploads/#{current_user.email}/bin_img | tail -n 1`
    render json: "/uploads/#{current_user.email}/bin_img/" + image_bin.delete!("\n")
  end

  def classify
    image_class = `ls -tr /home/bohdan/Desktop/recognazing/Recognizing/public/uploads/#{current_user.email}/class_img | tail -n 1`
    render json: "/uploads/#{current_user.email}/class_img/" + image_class.delete!("\n")
  end
end

app/controllers/resumes_controller.rb
class ResumesController < ApplicationController
  def index
    @resumes = current_user.resumes.all
  end

  def new
    @resume = Resume.new
  end

  def create
    @resume = Resume.new(resume_params.merge(user_id: current_user.id))

    if @resume.save
      Thread.new do
        att_name = @resume.attachment_url.split('/').last
        system("python3 lib/assets/background/main.py --file_name=public/uploads/#{current_user.email}/#{att_name} --file_txt_output=public/uploads/#{current_user.email}/Output.txt --file_video_output=public/uploads/#{current_user.email}/Output.avi --bin_img_path=public/uploads/#{current_user.email}/bin_img --class_img_path=public/uploads/#{current_user.email}/class_img")
      end
      redirect_to resumes_path, notice: "The resume #{@resume.name} has been uploaded."
    else
      render "new"
    end
  end

  def destroy
    @resume = Resume.find(params[:id])
    @resume.destroy
    redirect_to resumes_path, notice:  "The resume #{@resume.name} has been deleted."
  end

  private
    def resume_params
      params.require(:resume).permit(:name, :attachment)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @articles = Article.all.order('id asc')
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/resumes_helper.rb
module ResumesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_article.html.erb
<%= form_for @article do |f| %>
  <table align="center">
    <tbody>
    <tr>
      <td valign="middle">Title</td>
      <td class="column"><%= f.text_field :title, class: 'form-control' %></td>
    </tr>

    <tr>
      <td valign="middle">Preview</td>
      <td class="column"><%= f.text_field :preview, class: 'form-control' %></td>
    </tr>

    <tr>
      <td valign="middle">Content</td>
      <td class="text-field"><%= f.text_area :content, class: 'form-control' %></td>
    </tr>

    <tr>
      <td valign="middle">Thumbnail</td>
      <td class="column"><%= f.text_field :thumbnail, class: 'form-control' %></td>
    </tr>
    </tbody>
  </table>

  <div class="flex-container">
    <%= f.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<%= stylesheet_link_tag 'articles' %>

<h1 class="text-center">Edit article</h1>

<%= render 'article' %>

app/views/articles/new.html.erb
<%= stylesheet_link_tag 'articles' %>

<h1 class="text-center">Add new article</h1>

<%= render 'article' %>

app/views/articles/show.html.erb
<%= stylesheet_link_tag 'articles' %>

<div class="card text-white bg-dark mb-3">
  <table>
    <tr>
      <td>
        <%= image_tag(@article.thumbnail, class: 'card-img-top', alt: 'Card image cap') %>
      </td>
    </tr>
    <tr>
      <td>
        <div class="card-body">
          <h5 class="card-title"><%= @article.title %></h5>
          <p class="card-text"><%= @article.content %></p>
          <p class="card-text"><small class="text-muted"><%= @article.updated_at %></small></p>
        </div>
      </td>
    </tr>
  </table>
</div>

app/views/layouts/_alerts.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Recognizing</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= yield :javascript_includes %>
  </head>

  <body>
    <%= yield %>
    <%= render 'layouts/alerts' %>
  </body>
</html>

app/views/resumes/create.html.erb
<h1>Resumes#create</h1>
<p>Find me in app/views/resumes/create.html.erb</p>

app/views/resumes/destroy.html.erb
<h1>Resumes#destroy</h1>
<p>Find me in app/views/resumes/destroy.html.erb</p>

app/views/resumes/index.html.erb
<% content_for :javascript_includes do %>
  <%= javascript_include_tag 'images_watcher' %>
<% end %>

<h1>Traffic signs recognizing from video</h1>

<% if !flash[:notice].blank? %>
  <div class = "alert alert-info">
    <%= flash[:notice] %>
  </div>
<% end %>

<table class = "table table-bordered table-striped">
  <thead>
  <tr>
    <th>Name</th>
    <th>Download Link</th>
    <th> </th>
  </tr>
  </thead>

  <tbody>
  <% @resumes.each do |resume| %>

    <tr>
      <td><%= resume.name %></td>
      <td><%= link_to "Download Resume", resume.attachment_url %></td>
      <td><%= button_to "Delete",  resume, method: :delete, class: "btn btn-danger", confirm: "Are you sure that you wish to delete #{resume.name}?" %></td>
    </tr>

  <% end %>
  </tbody>
</table>

<div>
  <%= image_tag 'tem_car.jpeg', id: 'bin-image' %>
  <%= image_tag 'tem_car.jpeg', id: 'class-image' %>
</div>

app/views/resumes/new.html.erb
<h1>Recognize</h1>
<% if !@resume.errors.empty? %>
  <div class = "alert alert-error">

    <ul>
      <% @resume.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>

  </div>
<% end %>

<div class = "well">
  <%= form_for @resume, html: { multipart: true } do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <%= f.label :attachment %>
    <%= f.file_field :attachment %>
    <%= f.submit "Recognize", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/welcome/index.html.erb
<%= stylesheet_link_tag 'welcome' %>

<nav class="navbar navbar-expand-lg navbar-light bg-dark">
  <a class="navbar-brand" href="#">Traffic sign recognition</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <li class="nav-item active">
        <%= link_to 'Home', root_path, class: 'nav-link' %>
      </li>

      <% if current_user %>
        <li class="nav-item active">
          <%= link_to 'Your videos', resumes_path, class: 'nav-link' %>
        </li>
        <li class="nav-item active">
          <%= link_to 'Recognize', new_resume_path, class: 'nav-link' %>
        </li>
      <% end %>

      <li class="nav-item">
        <a class="nav-link" href="#">Traffic signs</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">About system</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">About author</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
    <% if current_user %>
      <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'btn btn-primary' %>
    <% else %>
      <%= link_to 'Sign Up', new_user_registration_path, class: 'btn btn-primary' %>
      <%= link_to 'Sign In', new_user_session_path, class: 'btn btn-primary' %>
    <% end %>
  </div>
</nav>

<main>
  <div class="row">
    <% @articles.each do |article| %>
      <div class="col-sm-3">
        <div class="card text-white bg-dark mb-3" style="width: 18rem;">
          <div class="auto-sized">
            <%= image_tag(article.thumbnail, class: 'card-img-top', alt: 'Card image cap') %>
          </div>
          <div class="card-body">
            <h5 class="card-title"><%= article.title %></h5>
            <p class="card-text"><%= article.preview %></p>
          </div>
          <a href="<%= article_path(article.id) %>" class="btn btn-primary">Get more</a>
        </div>
      </div>
    <% end %>
  </div>
</main>

<% if current_user.present? && current_user.is_admin %>
  <div>
    <%= link_to 'Add new article', new_article_path, class: 'btn btn-primary' %>
  </div>

  <table class="table table-hover table-dark">
    <thead>
      <tr>
        <td scope="col">Id</td>
        <td scope="col">Title</td>
        <td scope="col">Thumbnail</td>
        <td scope="col">Edit</td>
        <td scope="col">Delete</td>
      </tr>
    </thead>
    <tbody>
      <% @articles.each do |article| %>
        <tr>
          <td><%= article.id %></td>
          <td><%= article.title %></td>
          <td><%= article.thumbnail %></td>
          <td><%= link_to 'Edit', edit_article_path(article.id), class: 'btn btn-warning' %></td>
          <td><%= link_to 'Delete', article_path(article.id), class: 'btn btn-danger',method: :delete, data: {confirm: "Are you sure?"} %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>